# ===================================================================
# Spring Boot configuration for the "prod" profile.
# ===================================================================

logging:
    level:
        ROOT: INFO
        com.deepak.passwdservice: INFO
        io.github.jhipster: INFO

spring:
    devtools:
        restart:
            enabled: false
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


