# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        com.deepak.passwdservice: DEBUG
        io.github.jhipster: DEBUG

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
server:
    port: 8080
    
passwdfile:
  users:
    - name: root
      uid: 0
      gid: 0
      comment: root
      home: /root
      shell: /bin/bash
    - name: dwoodlins
      uid: 1001
      gid: 1001
      comment:
      home: /home/dwoodlins
      shell: /bin/false
  groups:
    - name: _analyticsusers
      gid: 250
      members: _analyticsd,_networkd,_timed
    - name: docker
      gid: 1002
      members: 