# ===================================================================
# Spring Boot configuration.
# ===================================================================

spring:
    application:
        name: passwdapi
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"


logging:
    file: target/passwdapi.log
    
    
passwdfile:
  user:
    - name: root
      uid: 0
      gid: 0
      comment: root
      home: /root
      shell: /bin/bash
    - name: dwoodlins
      uid: 1001
      gid: 1001
      comment:
      home: /home/dwoodlins
      shell: /bin/false

